# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  name = "Modules"
  url = "modules"
  weight = 20

[[main]]
  name = "People"
  url = "people"
  weight = 30

[[main]]
  name = "Assessment"
  url = "event"
  weight = 40

[[main]]
  name = "Publications, Presentations & Workshops"
  url = "publication"
  weight = 50

[[main]]
  name = "Feedback"
  url = "contact"
  weight = 60
